//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ark.Vinke.Facilities.Core.Service.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FtsResourcesCoreService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FtsResourcesCoreService() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ark.Vinke.Facilities.Core.Service.Properties.FtsResourcesCoreService", typeof(FtsResourcesCoreService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ark.Vinke.Facilities.Core.Service.{0}$.Captions.FtsCaptionRequiredFieldInvalid.
        /// </summary>
        public static string FtsCaptionRequiredFieldInvalid {
            get {
                return ResourceManager.GetString("FtsCaptionRequiredFieldInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ark.Vinke.Facilities.Core.Service.{0}$.Captions.FtsCaptionRequiredFieldMissing.
        /// </summary>
        public static string FtsCaptionRequiredFieldMissing {
            get {
                return ResourceManager.GetString("FtsCaptionRequiredFieldMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ark.Vinke.Facilities.Core.Service.{0}$.Captions.FtsCaptionTableNotFound.
        /// </summary>
        public static string FtsCaptionTableNotFound {
            get {
                return ResourceManager.GetString("FtsCaptionTableNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ark.Vinke.Facilities.Core.Service.{0}$.Exceptions.FtsExceptionIncrementControllerTableIncrementFieldNullOrEmpty.
        /// </summary>
        public static string FtsExceptionIncrementControllerTableIncrementFieldNullOrEmpty {
            get {
                return ResourceManager.GetString("FtsExceptionIncrementControllerTableIncrementFieldNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ark.Vinke.Facilities.Core.Service.{0}$.Exceptions.FtsExceptionIncrementControllerTableNameNullOrEmpty.
        /// </summary>
        public static string FtsExceptionIncrementControllerTableNameNullOrEmpty {
            get {
                return ResourceManager.GetString("FtsExceptionIncrementControllerTableNameNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ark.Vinke.Facilities.Core.Service.{0}$.Exceptions.FtsExceptionIncrementControllerTableParentKeyFieldsIdDomainInvalid.
        /// </summary>
        public static string FtsExceptionIncrementControllerTableParentKeyFieldsIdDomainInvalid {
            get {
                return ResourceManager.GetString("FtsExceptionIncrementControllerTableParentKeyFieldsIdDomainInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ark.Vinke.Facilities.Core.Service.{0}$.Exceptions.FtsExceptionIncrementControllerTableParentKeyFieldsIdDomainMissing.
        /// </summary>
        public static string FtsExceptionIncrementControllerTableParentKeyFieldsIdDomainMissing {
            get {
                return ResourceManager.GetString("FtsExceptionIncrementControllerTableParentKeyFieldsIdDomainMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ark.Vinke.Facilities.Core.Service.{0}$.Exceptions.FtsExceptionIncrementControllerTableKeyFieldsNullOrZeroLenght.
        /// </summary>
        public static string FtsExceptionIncrementControllerTableParentKeyFieldsNullOrZeroLenght {
            get {
                return ResourceManager.GetString("FtsExceptionIncrementControllerTableParentKeyFieldsNullOrZeroLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ark.Vinke.Facilities.Core.Service.{0}$.Exceptions.FtsExceptionIncrementDataTableIncrementKeyMissing.
        /// </summary>
        public static string FtsExceptionIncrementDataTableIncrementKeyMissing {
            get {
                return ResourceManager.GetString("FtsExceptionIncrementDataTableIncrementKeyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ark.Vinke.Facilities.Core.Service.{0}$.Exceptions.FtsExceptionIncrementDataTableParentKeyFieldsIdDomainInvalid.
        /// </summary>
        public static string FtsExceptionIncrementDataTableParentKeyFieldsIdDomainInvalid {
            get {
                return ResourceManager.GetString("FtsExceptionIncrementDataTableParentKeyFieldsIdDomainInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ark.Vinke.Facilities.Core.Service.{0}$.Exceptions.FtsExceptionIncrementDataTableParentKeyMissing.
        /// </summary>
        public static string FtsExceptionIncrementDataTableParentKeyMissing {
            get {
                return ResourceManager.GetString("FtsExceptionIncrementDataTableParentKeyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ark.Vinke.Facilities.Core.Service.{0}$.Exceptions.FtsExceptionIncrementRangeLowerThanOne.
        /// </summary>
        public static string FtsExceptionIncrementRangeLowerThanOne {
            get {
                return ResourceManager.GetString("FtsExceptionIncrementRangeLowerThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ark.Vinke.Facilities.Core.Service.{0}$.Exceptions.FtsExceptionIncrementTableKeyFieldNullOrEmpty.
        /// </summary>
        public static string FtsExceptionIncrementTableKeyFieldNullOrEmpty {
            get {
                return ResourceManager.GetString("FtsExceptionIncrementTableKeyFieldNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ark.Vinke.Facilities.Core.Service.{0}$.Exceptions.FtsExceptionIncrementTableNameNotFound.
        /// </summary>
        public static string FtsExceptionIncrementTableNameNotFound {
            get {
                return ResourceManager.GetString("FtsExceptionIncrementTableNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ark.Vinke.Facilities.Core.Service.{0}$.Exceptions.FtsExceptionIncrementTableNameNullOrEmpty.
        /// </summary>
        public static string FtsExceptionIncrementTableNameNullOrEmpty {
            get {
                return ResourceManager.GetString("FtsExceptionIncrementTableNameNullOrEmpty", resourceCulture);
            }
        }
    }
}
