//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ark.Vinke.System.Core.Service.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SysResourcesCoreService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysResourcesCoreService() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ark.Vinke.System.Core.Service.Properties.SysResourcesCoreService", typeof(SysResourcesCoreService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ark.Vinke.System.Core.Service.{0}$.Captions.SysCaptionDenied.
        /// </summary>
        public static string SysCaptionDenied {
            get {
                return ResourceManager.GetString("SysCaptionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ark.Vinke.System.Core.Service.{0}$.Captions.SysCaptionIdDomain.
        /// </summary>
        public static string SysCaptionIdDomain {
            get {
                return ResourceManager.GetString("SysCaptionIdDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ark.Vinke.System.Core.Service.{0}$.Captions.SysCaptionIdRole.
        /// </summary>
        public static string SysCaptionIdRole {
            get {
                return ResourceManager.GetString("SysCaptionIdRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ark.Vinke.System.Core.Service.{0}$.Captions.SysCaptionInvalidType.
        /// </summary>
        public static string SysCaptionInvalidType {
            get {
                return ResourceManager.GetString("SysCaptionInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ark.Vinke.System.Core.Service.{0}$.Captions.SysCaptionName.
        /// </summary>
        public static string SysCaptionName {
            get {
                return ResourceManager.GetString("SysCaptionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ark.Vinke.System.Core.Service.{0}$.Captions.SysCaptionSuccess.
        /// </summary>
        public static string SysCaptionSuccess {
            get {
                return ResourceManager.GetString("SysCaptionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ark.Vinke.System.Core.Service.{0}$.Exceptions.SysExceptionAuthenticationFailed.
        /// </summary>
        public static string SysExceptionAuthenticationFailed {
            get {
                return ResourceManager.GetString("SysExceptionAuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ark.Vinke.System.Core.Service.{0}$.Exceptions.SysExceptionAutomationInvalidService.
        /// </summary>
        public static string SysExceptionAutomationInvalidService {
            get {
                return ResourceManager.GetString("SysExceptionAutomationInvalidService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ark.Vinke.System.Core.Service.{0}$.Messages.SysMessageSuccess.
        /// </summary>
        public static string SysMessageSuccess {
            get {
                return ResourceManager.GetString("SysMessageSuccess", resourceCulture);
            }
        }
    }
}
