//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ark.Vinke.Studio.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesStudio {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesStudio() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ark.Vinke.Studio.Properties.ResourcesStudio", typeof(ResourcesStudio).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a echo Building Ark.{DEVELOPER}.{MODULE}...
        ///dotnet clean &gt;&gt; nul
        ///dotnet build --configuration Debug &gt;&gt; nul
        ///.
        /// </summary>
        public static string Ark_Developer_Module_Builder_Debug_bat {
            get {
                return ResourceManager.GetString("Ark_Developer_Module_Builder_Debug_bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a echo Building Ark.{DEVELOPER}.{MODULE}...
        ///dotnet clean &gt;&gt; nul
        ///dotnet build --configuration Release &gt;&gt; nul
        ///.
        /// </summary>
        public static string Ark_Developer_Module_Builder_Release_bat {
            get {
                return ResourceManager.GetString("Ark_Developer_Module_Builder_Release_bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;Project Sdk=&quot;Microsoft.NET.Sdk&quot;&gt;
        ///
        ///	&lt;PropertyGroup&gt;
        ///		&lt;TargetFramework&gt;net6.0&lt;/TargetFramework&gt;
        ///		&lt;Product&gt;Ark&lt;/Product&gt;
        ///		&lt;Description&gt;Ark {DEVELOPER} {MODULE}&lt;/Description&gt;
        ///		&lt;Authors&gt;{DEVELOPER}&lt;/Authors&gt;
        ///		&lt;Version&gt;1.0.0&lt;/Version&gt;
        ///		&lt;RepositoryUrl&gt;{REPOSITORY}&lt;/RepositoryUrl&gt;
        ///		&lt;GeneratePackageOnBuild&gt;true&lt;/GeneratePackageOnBuild&gt;
        ///		&lt;PackageRequireLicenseAcceptance&gt;true&lt;/PackageRequireLicenseAcceptance&gt;
        ///		&lt;PackageLicenseFile&gt;LICENSE&lt;/PackageLicenseFile&gt;
        ///		&lt;PackageOutputPath&gt;$(SolutionDir)..\ [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string Ark_Developer_Module_csproj {
            get {
                return ResourceManager.GetString("Ark_Developer_Module_csproj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;Project Sdk=&quot;Microsoft.NET.Sdk&quot;&gt;
        ///
        ///	&lt;PropertyGroup&gt;
        ///		&lt;TargetFramework&gt;net6.0-windows&lt;/TargetFramework&gt;
        ///		&lt;Product&gt;Ark&lt;/Product&gt;
        ///		&lt;Description&gt;Ark {DEVELOPER} {MODULE} {PROJECT} Client&lt;/Description&gt;
        ///		&lt;Authors&gt;{DEVELOPER}&lt;/Authors&gt;
        ///		&lt;Version&gt;1.0.0&lt;/Version&gt;
        ///		&lt;RepositoryUrl&gt;{REPOSITORY}&lt;/RepositoryUrl&gt;
        ///		&lt;GeneratePackageOnBuild&gt;true&lt;/GeneratePackageOnBuild&gt;
        ///		&lt;PackageRequireLicenseAcceptance&gt;true&lt;/PackageRequireLicenseAcceptance&gt;
        ///		&lt;PackageLicenseFile&gt;LICENSE&lt;/PackageLicenseFile&gt;
        ///		&lt;PackageOut [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string Ark_Developer_Module_Project_Client_csproj {
            get {
                return ResourceManager.GetString("Ark_Developer_Module_Project_Client_csproj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;Project Sdk=&quot;Microsoft.NET.Sdk&quot;&gt;
        ///
        ///	&lt;PropertyGroup&gt;
        ///		&lt;TargetFramework&gt;net6.0&lt;/TargetFramework&gt;
        ///		&lt;Product&gt;Ark&lt;/Product&gt;
        ///		&lt;Description&gt;Ark {DEVELOPER} {MODULE} {PROJECT}&lt;/Description&gt;
        ///		&lt;Authors&gt;{DEVELOPER}&lt;/Authors&gt;
        ///		&lt;Version&gt;1.0.0&lt;/Version&gt;
        ///		&lt;RepositoryUrl&gt;{REPOSITORY}&lt;/RepositoryUrl&gt;
        ///		&lt;GeneratePackageOnBuild&gt;true&lt;/GeneratePackageOnBuild&gt;
        ///		&lt;PackageRequireLicenseAcceptance&gt;true&lt;/PackageRequireLicenseAcceptance&gt;
        ///		&lt;PackageLicenseFile&gt;LICENSE&lt;/PackageLicenseFile&gt;
        ///		&lt;PackageOutputPath&gt;$(Solut [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string Ark_Developer_Module_Project_csproj {
            get {
                return ResourceManager.GetString("Ark_Developer_Module_Project_csproj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;Project Sdk=&quot;Microsoft.NET.Sdk&quot;&gt;
        ///
        ///	&lt;PropertyGroup&gt;
        ///		&lt;TargetFramework&gt;net6.0&lt;/TargetFramework&gt;
        ///		&lt;Product&gt;Ark&lt;/Product&gt;
        ///		&lt;Description&gt;Ark {DEVELOPER} {MODULE} {PROJECT} Data&lt;/Description&gt;
        ///		&lt;Authors&gt;{DEVELOPER}&lt;/Authors&gt;
        ///		&lt;Version&gt;1.0.0&lt;/Version&gt;
        ///		&lt;RepositoryUrl&gt;{REPOSITORY}&lt;/RepositoryUrl&gt;
        ///		&lt;GeneratePackageOnBuild&gt;true&lt;/GeneratePackageOnBuild&gt;
        ///		&lt;PackageRequireLicenseAcceptance&gt;true&lt;/PackageRequireLicenseAcceptance&gt;
        ///		&lt;PackageLicenseFile&gt;LICENSE&lt;/PackageLicenseFile&gt;
        ///		&lt;PackageOutputPath&gt;$( [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string Ark_Developer_Module_Project_Data_csproj {
            get {
                return ResourceManager.GetString("Ark_Developer_Module_Project_Data_csproj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;Project Sdk=&quot;Microsoft.NET.Sdk&quot;&gt;
        ///
        ///	&lt;PropertyGroup&gt;
        ///		&lt;TargetFramework&gt;net6.0&lt;/TargetFramework&gt;
        ///		&lt;Product&gt;Ark&lt;/Product&gt;
        ///		&lt;Description&gt;Ark {DEVELOPER} {MODULE} {PROJECT} IPlugin&lt;/Description&gt;
        ///		&lt;Authors&gt;{DEVELOPER}&lt;/Authors&gt;
        ///		&lt;Version&gt;1.0.0&lt;/Version&gt;
        ///		&lt;RepositoryUrl&gt;{REPOSITORY}&lt;/RepositoryUrl&gt;
        ///		&lt;GeneratePackageOnBuild&gt;true&lt;/GeneratePackageOnBuild&gt;
        ///		&lt;PackageRequireLicenseAcceptance&gt;true&lt;/PackageRequireLicenseAcceptance&gt;
        ///		&lt;PackageLicenseFile&gt;LICENSE&lt;/PackageLicenseFile&gt;
        ///		&lt;PackageOutputPath [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string Ark_Developer_Module_Project_IPlugin_csproj {
            get {
                return ResourceManager.GetString("Ark_Developer_Module_Project_IPlugin_csproj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;Project Sdk=&quot;Microsoft.NET.Sdk&quot;&gt;
        ///
        ///	&lt;PropertyGroup&gt;
        ///		&lt;TargetFramework&gt;net6.0&lt;/TargetFramework&gt;
        ///		&lt;Product&gt;Ark&lt;/Product&gt;
        ///		&lt;Description&gt;Ark {DEVELOPER} {MODULE} {PROJECT} IServer&lt;/Description&gt;
        ///		&lt;Authors&gt;{DEVELOPER}&lt;/Authors&gt;
        ///		&lt;Version&gt;1.0.0&lt;/Version&gt;
        ///		&lt;RepositoryUrl&gt;{REPOSITORY}&lt;/RepositoryUrl&gt;
        ///		&lt;GeneratePackageOnBuild&gt;true&lt;/GeneratePackageOnBuild&gt;
        ///		&lt;PackageRequireLicenseAcceptance&gt;true&lt;/PackageRequireLicenseAcceptance&gt;
        ///		&lt;PackageLicenseFile&gt;LICENSE&lt;/PackageLicenseFile&gt;
        ///		&lt;PackageOutputPath [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string Ark_Developer_Module_Project_IServer_csproj {
            get {
                return ResourceManager.GetString("Ark_Developer_Module_Project_IServer_csproj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;Project Sdk=&quot;Microsoft.NET.Sdk&quot;&gt;
        ///
        ///	&lt;PropertyGroup&gt;
        ///		&lt;TargetFramework&gt;net6.0&lt;/TargetFramework&gt;
        ///		&lt;Product&gt;Ark&lt;/Product&gt;
        ///		&lt;Description&gt;Ark {DEVELOPER} {MODULE} {PROJECT} IService&lt;/Description&gt;
        ///		&lt;Authors&gt;{DEVELOPER}&lt;/Authors&gt;
        ///		&lt;Version&gt;1.0.0&lt;/Version&gt;
        ///		&lt;RepositoryUrl&gt;{REPOSITORY}&lt;/RepositoryUrl&gt;
        ///		&lt;GeneratePackageOnBuild&gt;true&lt;/GeneratePackageOnBuild&gt;
        ///		&lt;PackageRequireLicenseAcceptance&gt;true&lt;/PackageRequireLicenseAcceptance&gt;
        ///		&lt;PackageLicenseFile&gt;LICENSE&lt;/PackageLicenseFile&gt;
        ///		&lt;PackageOutputPat [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string Ark_Developer_Module_Project_IService_csproj {
            get {
                return ResourceManager.GetString("Ark_Developer_Module_Project_IService_csproj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;Project Sdk=&quot;Microsoft.NET.Sdk&quot;&gt;
        ///
        ///	&lt;PropertyGroup&gt;
        ///		&lt;TargetFramework&gt;net6.0&lt;/TargetFramework&gt;
        ///		&lt;Product&gt;Ark&lt;/Product&gt;
        ///		&lt;Description&gt;Ark {DEVELOPER} {MODULE} {PROJECT} Plugin&lt;/Description&gt;
        ///		&lt;Authors&gt;{DEVELOPER}&lt;/Authors&gt;
        ///		&lt;Version&gt;1.0.0&lt;/Version&gt;
        ///		&lt;RepositoryUrl&gt;{REPOSITORY}&lt;/RepositoryUrl&gt;
        ///		&lt;GeneratePackageOnBuild&gt;true&lt;/GeneratePackageOnBuild&gt;
        ///		&lt;PackageRequireLicenseAcceptance&gt;true&lt;/PackageRequireLicenseAcceptance&gt;
        ///		&lt;PackageLicenseFile&gt;LICENSE&lt;/PackageLicenseFile&gt;
        ///		&lt;PackageOutputPath&gt; [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string Ark_Developer_Module_Project_Plugin_csproj {
            get {
                return ResourceManager.GetString("Ark_Developer_Module_Project_Plugin_csproj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;Project Sdk=&quot;Microsoft.NET.Sdk&quot;&gt;
        ///
        ///	&lt;PropertyGroup&gt;
        ///		&lt;TargetFramework&gt;net6.0&lt;/TargetFramework&gt;
        ///		&lt;Product&gt;Ark&lt;/Product&gt;
        ///		&lt;Description&gt;Ark {DEVELOPER} {MODULE} {PROJECT} Servant&lt;/Description&gt;
        ///		&lt;Authors&gt;{DEVELOPER}&lt;/Authors&gt;
        ///		&lt;Version&gt;1.0.0&lt;/Version&gt;
        ///		&lt;RepositoryUrl&gt;{REPOSITORY}&lt;/RepositoryUrl&gt;
        ///		&lt;GeneratePackageOnBuild&gt;true&lt;/GeneratePackageOnBuild&gt;
        ///		&lt;PackageRequireLicenseAcceptance&gt;true&lt;/PackageRequireLicenseAcceptance&gt;
        ///		&lt;PackageLicenseFile&gt;LICENSE&lt;/PackageLicenseFile&gt;
        ///		&lt;PackageOutputPath [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string Ark_Developer_Module_Project_Servant_csproj {
            get {
                return ResourceManager.GetString("Ark_Developer_Module_Project_Servant_csproj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;Project Sdk=&quot;Microsoft.NET.Sdk.Web&quot;&gt;
        ///
        ///	&lt;PropertyGroup&gt;
        ///		&lt;TargetFramework&gt;net6.0&lt;/TargetFramework&gt;
        ///		&lt;Product&gt;Ark&lt;/Product&gt;
        ///		&lt;Description&gt;Ark {DEVELOPER} {MODULE} {PROJECT} Server&lt;/Description&gt;
        ///		&lt;Authors&gt;{DEVELOPER}&lt;/Authors&gt;
        ///		&lt;Version&gt;1.0.0&lt;/Version&gt;
        ///		&lt;RepositoryUrl&gt;{REPOSITORY}&lt;/RepositoryUrl&gt;
        ///		&lt;GeneratePackageOnBuild&gt;true&lt;/GeneratePackageOnBuild&gt;
        ///		&lt;PackageRequireLicenseAcceptance&gt;true&lt;/PackageRequireLicenseAcceptance&gt;
        ///		&lt;PackageLicenseFile&gt;LICENSE&lt;/PackageLicenseFile&gt;
        ///		&lt;PackageOutputP [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string Ark_Developer_Module_Project_Server_csproj {
            get {
                return ResourceManager.GetString("Ark_Developer_Module_Project_Server_csproj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;Project Sdk=&quot;Microsoft.NET.Sdk&quot;&gt;
        ///
        ///	&lt;PropertyGroup&gt;
        ///		&lt;TargetFramework&gt;net6.0&lt;/TargetFramework&gt;
        ///		&lt;Product&gt;Ark&lt;/Product&gt;
        ///		&lt;Description&gt;Ark {DEVELOPER} {MODULE} {PROJECT} Service&lt;/Description&gt;
        ///		&lt;Authors&gt;{DEVELOPER}&lt;/Authors&gt;
        ///		&lt;Version&gt;1.0.0&lt;/Version&gt;
        ///		&lt;RepositoryUrl&gt;{REPOSITORY}&lt;/RepositoryUrl&gt;
        ///		&lt;GeneratePackageOnBuild&gt;true&lt;/GeneratePackageOnBuild&gt;
        ///		&lt;PackageRequireLicenseAcceptance&gt;true&lt;/PackageRequireLicenseAcceptance&gt;
        ///		&lt;PackageLicenseFile&gt;LICENSE&lt;/PackageLicenseFile&gt;
        ///		&lt;PackageOutputPath [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string Ark_Developer_Module_Project_Service_csproj {
            get {
                return ResourceManager.GetString("Ark_Developer_Module_Project_Service_csproj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 
        ///Microsoft Visual Studio Solution File, Format Version 12.00
        ///# Visual Studio Version 17
        ///VisualStudioVersion = 17.4.33213.308
        ///MinimumVisualStudioVersion = 10.0.40219.1
        ///Project(&quot;{9A19103F-16F7-4668-BE54-9A1E7A4F7556}&quot;) = &quot;Ark.{DEVELOPER}.{MODULE}&quot;, &quot;Ark.{DEVELOPER}.{MODULE}\Ark.{DEVELOPER}.{MODULE}.csproj&quot;, &quot;{GUID-ARK-DEVELOPER-MODULE}&quot;
        ///EndProject
        ///Project(&quot;{9A19103F-16F7-4668-BE54-9A1E7A4F7556}&quot;) = &quot;Ark.{DEVELOPER}.{MODULE}.{PROJECT}&quot;, &quot;Ark.{DEVELOPER}.{MODULE}.{PROJECT}\Ark.{DEVELOPER}.{MODULE}.{PROJE [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string Ark_Developer_Module_sln {
            get {
                return ResourceManager.GetString("Ark_Developer_Module_sln", resourceCulture);
            }
        }
    }
}
